### PR TITLE
dependencies and readme updates

### PR DESCRIPTION
**Pull request by Amaca**
I updated all the dependencies on package.json. I also added some information on readme about Webpack 5 and html-webpack plugin. I installed everything and tested locally, it seems working fine with my configuration. I am using node 19.0.0

### CODE REVIEW

**Comment by Epimodev** [comment]
Thanks a lot for this merge request!

Everything looks good for me but before merge and publish I just to be sure about one detail:
When you say it's working did you check if the sprite is well generated an injected in your built html? I just want to be sure svg-sprite upgrade to `2.0.2` doesn't break anything

**Comment by Amaca** [comment]
Yes, i installed my forked updated version with npm and tested on a personal project. The install was fine, no problems at all. I tested using some svgs and they are added easly on compiled html. i think everything is fine. Anyway if you want to try, this is the updated forked repo:  [svg-sprite-html-webpack forked](https://github.com/Amaca/svg-sprite)

This is a screenshot with the input and output of a logo in my personal test page:
 
testing

**Comment by Epimodev** [comment]
This perfect thanks a lot! I merge it and add a comment here when this is published

**Comment by Epimodev** [comment]
I just published version `v2.4.1` with your changes!

**Comment by Amaca** [comment]
Thank you so much! i tried an installation directly from npm and it works perfectly in my machine. Thank you for support and for this great plugin.

**Pull request merged**
